---
title: "Mar 28 Stuff"
author: "Jon Matkin"
date: '2023-03-28'
output: html_document
---

```{r setup, include=FALSE}
library(randomForest)
data_car <- read.csv(file.choose(),header=TRUE)
head(data_car)
```

```{r}
colnames(data_car) <- c("BuyingPrice","Maintenance","NumDoors","NumPersons","BootSpace","Safety","Condition")
head(data_car)
str(data_car)
```

```{r}
levels(data_car$Condition)
summary(data_car)
```
```{r}
set.seed(100)
train <- sample(nrow(data_car), 0.7*nrow(data_car),replace=FALSE)
train_data <- data_car[train,]
test_data <- data_car[-train,]
summary(train_data)
summary(test_data)
```

```{r}
model1 <- randomForest(as.factor(Condition) ~., data=train_data, importance=TRUE)
model1
```
```{r}
model2 <- randomForest(as.factor(Condition) ~., data= train_data, ntree=500, mtry = 6, importance=TRUE)
model2
```

```{r}
pred_train <- predict(model2,data_train,type="class")
table(pred_train, data_train$Condition)
```

```{r}
pred_test <- predict(model2,data_test,type="class")
table(pred_test, data_test$Condition)
```

```{r}
importance(model2)
varImpPlot(model2)
```

```{r}
a=c()
i = 5
for (i in 3:8){
  model3 <- randomForest(as.factor(Condition) ~., data=train_data, ntree=500, mtry=i, importance=TRUE)
  pred_test = predict(model3, test_data, type="class")
  a[i-2] = mean(pred_test == test_data$Condition)
}

a
plot(3:8,a)
```

```{r}
library(rpart)
library(caret)
library(e1071)

model_dt <- train(Condition ~., data=train_data, method="rpart")
model_dt1 <- predict(model_dt, data=train_data)
table(model_dt1, train_data$Condition)
mean(model_dt1 == train_data$Condition)

model_dt_test <- predict(model_dt, data=test_data)
table(model_dt_test, test_data$Condition)
mean(model_dt_test == test_data$Condition)
```


